[package]
name = "buckets"
version = "0.1.0"
authors = ["Daniel Lim <orcas@octalorca.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
handlebars = "3.5.3"
